export const CHANGE_SEARCH_FIELD = 'CHANGE_SEARCH_FIELD';
export const SELECT_REGION = 'SELECT_REGION';
export const REQUEST_COUNTRIES_PENDING = 'REQUEST_COUNTRIES_PENDING';
export const REQUEST_COUNTRIES_SUCCESS = 'REQUEST_COUNTRIES_SUCCESS';
export const REQUEST_COUNTRIES_FAIL = 'REQUEST_COUNTRIES_FAIL';
export const SELECT_COUNTRY = 'SELECT_COUNTRY';